root: true
extends:
  - airbnb-base
  - plugin:import/errors
  - prettier
plugins:
  - prettier
env:
  node: true
globals:
  COSAlertWindow: true
  MSApplicationMetadata: true
  NSAlertFirstButtonReturn: true
  NSButtonCell: true
  NSComboBox: true
  NSImage: true
  NSMakeRect: true
  NSMakeSize: true
  NSMatrix: true
  NSRadioButton: true
  NSRadioModeMatrix: true
  NSString: true
  NSURL: true
  NSURLSession: true
  NSUserDefaults: true
  NSUUID: true
rules:
  'import/prefer-default-export': 0
  'import/no-unresolved': 0
  'global-require': 0
  'no-underscore-dangle': 0
  'no-await-in-loop': 0
